from __future__ import annotations

from pathlib import Path
import random
import shutil
import subprocess

from orchestrator.schemas import CandidateReport, CandidateSpec, read_json, write_json
from orchestrator.templates import render_strategy


def run_candidate(repo_root: Path, candidate_dir: Path, spec: CandidateSpec) -> CandidateReport:
    candidate_dir.mkdir(parents=True, exist_ok=True)
    write_json(candidate_dir / "spec.json", spec.to_dict())
    (candidate_dir / "main.py").write_text(render_strategy(spec))
    write_json(candidate_dir / "config.json", {"local-id": random.randint(100000000, 999999999)})

    output_dir = candidate_dir / "backtest"
    if output_dir.exists():
        shutil.rmtree(output_dir)
    command = [
        "lean",
        "backtest",
        str(candidate_dir),
        "--output",
        str(output_dir),
        "--lean-config",
        str(repo_root / "lean.json"),
        "--no-update",
    ]

    result = subprocess.run(
        command,
        cwd=repo_root,
        text=True,
        capture_output=True,
    )

    summary_files = sorted(output_dir.glob("*-summary.json"))
    errors: list[str] = []
    notes: list[str] = []
    if result.returncode != 0:
        errors.append(f"lean backtest exited with code {result.returncode}")
    if result.stderr.strip():
        notes.append(result.stderr.strip())
    if result.stdout.strip():
        notes.append(result.stdout.strip())

    if not summary_files:
        report = CandidateReport(
            candidate_id=spec.candidate_id,
            status="failed",
            metrics={},
            errors=errors + ["No summary file generated by LEAN."],
            notes=notes,
            output_dir=str(output_dir),
        )
        write_json(candidate_dir / "result.json", report.to_dict())
        return report

    summary = read_json(summary_files[-1])
    report = _build_report(spec, summary, errors, notes, output_dir)
    write_json(candidate_dir / "result.json", report.to_dict())
    return report


def _build_report(
    spec: CandidateSpec,
    summary: dict,
    errors: list[str],
    notes: list[str],
    output_dir: Path,
) -> CandidateReport:
    state = summary.get("state", {})
    statistics = summary.get("statistics", {})
    total_performance = summary.get("totalPerformance", {})
    portfolio_stats = total_performance.get("portfolioStatistics", {})
    trade_stats = total_performance.get("tradeStatistics", {})

    status = "completed" if state.get("Status") == "Completed" else "failed"
    runtime_error = state.get("RuntimeError", "")
    if runtime_error:
        errors.append(runtime_error.strip())

    metrics = {
        "family": spec.family,
        "net_profit_pct": _to_float(statistics.get("Net Profit")),
        "sharpe_ratio": _to_float(statistics.get("Sharpe Ratio")),
        "sortino_ratio": _to_float(statistics.get("Sortino Ratio")),
        "max_drawdown_pct": _to_float(statistics.get("Drawdown")),
        "win_rate_pct": _to_float(statistics.get("Win Rate")),
        "loss_rate_pct": _to_float(statistics.get("Loss Rate")),
        "total_orders": _to_float(statistics.get("Total Orders")),
        "portfolio_turnover_pct": _to_float(statistics.get("Portfolio Turnover")),
        "trade_count": _to_float(trade_stats.get("totalNumberOfTrades")),
        "ending_equity": _to_float(portfolio_stats.get("endEquity")),
    }

    return CandidateReport(
        candidate_id=spec.candidate_id,
        status=status,
        metrics=metrics,
        errors=errors,
        notes=notes,
        output_dir=str(output_dir),
    )


def _to_float(value) -> float:
    if value is None:
        return 0.0
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        cleaned = (
            value.replace("%", "")
            .replace("$", "")
            .replace(",", "")
            .strip()
        )
        if cleaned == "":
            return 0.0
        try:
            return float(cleaned)
        except ValueError:
            return 0.0
    return 0.0
